Store sailbot gps
UBCSailbot/local-pathfinding pull request #161
Opened 2020-11-14 21:55 UTC by JoshuaJSam

To address: https://github.com/UBCSailbot/local-pathfinding/issues/129

Created an independent ros node that subscribes to the sailbot GPS. Every second stores the sailbot GPS. Then at the end, plots the full path that the boat took (see how jagged or uneven it is) and total displacement from starting point.

2020-11-14 22:04 UTC, JoshuaJSam commented
@tylerlum I tried using some existing code from log_closest_obstacle.py which creates a png plot at the end. The code using "ABS_PATH_TO_OUTPUT_SAILBOT_GPS_DISPLACEMENT" . I am getting an error though outputing the plot

2020-11-15 02:28 UTC, tylerlum requested changes
Add this to the `all.launch` file like log_closest_obstacle.py.

Also, you may need to run `chmod +x python/store_sailbot_gps.py` to ensure that this can be executable

2020-11-15 02:28 UTC, tylerlum commented on python/store_sailbot_gps.py
> +    rospy.loginfo("hi")
Change this to "Saving to {}".format(ABS_PATH_TO_OUTPUT_SAILBOT_GPS_DISPLACEMENT)

2020-11-19 06:32 UTC, JoshuaJSam commented
@tylerlum Its finished now :)

2020-11-21 00:11 UTC, JoshuaJSam commented
@patrick-5546 If you would like to review this PR its functionality is pretty straightforward. If it is working properly then it will create a numpy plot of the displacement in a local-pathfinding folder where the other plots are stored as well. It should print out the file path after you CTRL+C and end the ros simulation.

2020-11-21 19:20 UTC, patrick-5546 reviewed
Looks good to me. You can see where and what your lint errors are by clicking details.

2020-11-21 19:20 UTC, patrick-5546 commented on python/store_sailbot_gps.py
> +    rospy.init_node('SailbotGPSData')
For clarity, this line can go in `__init__()` of `SailbotGPSData`

2020-11-21 19:20 UTC, patrick-5546 commented on python/store_sailbot_gps.py
> +        rospy.sleep(UPDATE_TIME_SECONDS)
For clarity, this can go inside `while not rospy.is._shutdown()`

2020-11-27 07:58 UTC, tylerlum approved these changes
Awesome work! Feel free to merge

2020-11-27 15:20 UTC, merged