Add smooth changes in heading and speed
UBCSailbot/local-pathfinding pull request #162
Opened 2020-11-27 05:16 UTC by haakov

Fixes https://github.com/UBCSailbot/local-pathfinding/issues/144

2020-11-27 07:57 UTC, tylerlum requested changes
Looks great! Added a couple of comments. 

Also, it would be great if this could be turned on/off with a rostopic or rosparam (might be easier with rosparam)

2020-11-27 07:57 UTC, tylerlum commented on python/MOCK_controller_and_boat.py
> +BOAT_SPEED_KMPH = 14.4  # Boat should move at about 4m/s = 14.4 km/h
Great clear variable names

2020-11-27 07:57 UTC, tylerlum commented on python/MOCK_controller_and_boat.py
> +# TODO: Move this to utilities
Good idea to move this to utilities :)

2020-11-27 07:57 UTC, tylerlum commented on python/MOCK_controller_and_boat.py
> +# TODO: Move this to utilities
If moved to utilities, might be good to specify degrees in func name or var name

2020-11-27 07:57 UTC, tylerlum commented on python/MOCK_controller_and_boat.py
> +        self.speedKmph = self.speedKmph / max(1, min(3, error_mag / 45))
Potentially change speed setpoint based on wind direction

2020-11-27 07:57 UTC, tylerlum commented on python/MOCK_controller_and_boat.py
> +        error = ssa(self.headingSetpoint - self.headingDegrees)
Great work, looks clear to me

2021-01-15 06:02 UTC, haakov commented on python/MOCK_controller_and_boat.py
> +        self.speedKmph = self.speedKmph / max(1, min(3, error_mag / 45))
Done! :)

2021-01-15 06:03 UTC, haakov commented
Wind setpoint is now divided by four when going upwind or downwind

2021-02-18 19:50 UTC, tylerlum approved these changes
Sorry totally forgot to review this again. Looks great! Tried it out and seems to work nicely. Just need to fix merge conflicts then good to go!

2021-02-18 19:50 UTC, tylerlum commented
And fix lint :)

2021-02-18 20:16 UTC, merged