Revise waypoint reached
UBCSailbot/local-pathfinding pull request #172
Opened 2020-12-11 20:43 UTC by patrick-5546

Addresses #171.

2020-12-11 20:50 UTC, patrick-5546 commented on python/Path.py
> +        return self.waypointReached(positionLatlon, previousWaypointLatlon, nextWaypointLatlon)
Issues with this implementation:
* Returns true every time the simulation starts
* Assumes that there are at least 2 elements in `self._latlons`

2021-01-08 05:26 UTC, tylerlum reviewed
Looks good to me so far. Update the unit tests to ensure proper functionality. I will do some testing myself and approve after :)

2021-01-09 21:44 UTC, tylerlum requested changes
Great work. Make sure to add in those unit tests to gain confidence in the code, and double check the verticalShift math.

2021-01-16 19:25 UTC, tylerlum approved these changes
Works beautifully. Might still be a good idea to draw the boundary line in another PR. Go ahead and merge.

2021-01-16 19:38 UTC, merged