Log AIS Ships
UBCSailbot/local-pathfinding pull request #234
Opened 2021-08-26 20:15 UTC by patrick-5546

Resolves #233 

1. Creates a log file for AIS ships every time `get_real_ships()` is called in the directory `ais_ships_log/`
    - Turn on logging by adding `log_exactais:=true` to the roslaunch command
2. Simple analysis of exactAIS data
    - Note: the headings saved from exactAIS data are misleadingly named: they are NOT the same units as headingDegrees in the pathfinding code. To convert to heading degrees, use the `bearingToHeadingDegrees` function in utilities.py

2021-09-14 23:06 UTC, tylerlum requested changes
Looks good but a few suggestions:

exactais_scraper.py and exactais_ships_analysis.py look very independent of all other parts of this code. Could you put these in their own folder, probably not inside python directory but outside. Something like `exactais_analysis`. Since this is not pathfinding code, we can keep it away. Same with heatmap.txt put in there too

Also, add a rosparam for the logging. May take up a lot of space to store at all times.

2021-09-16 16:00 UTC, patrick-5546 commented
Example of bounding boxes in the scraped exactAIS data for `dimension=5`
![image](https://user-images.githubusercontent.com/65756895/133645788-46c73c3b-8d66-44ec-8cdd-bd8b0bbeb2a6.png)

2021-09-16 16:15 UTC, patrick-5546 commented
Quick observations from tracking boats in bounding boxes *(n,n)* for *n* in [0,4]:
- Boat behavior does not seem to be dependent on where it is located in the ocean (aka which bounding box it is in)
- There are different types of boats that have different behaviors
    - Some boats maintain a constant speed (±1 knot) and heading (±5 degrees): bulk carrier
        - Some reported the exact same speed and heading for 8 hours
    - Some boats vary greatly in speed and heading, but are very slow in general, like a research vessel

2021-09-16 16:58 UTC, tylerlum commented
Awesome, can you put some of the speed and heading plots here? Would be great to have it recorded and also potentially model the research vessels :)

2021-09-16 17:00 UTC, tylerlum approved these changes

2021-09-16 17:00 UTC, tylerlum commented on python/MOCK_exactAIS.py
> +        now = datetime.datetime.now()
Add a check like rosparam get here and in launch file, then good to merge!

2021-09-16 17:00 UTC, patrick-5546 commented
> Awesome, can you put some of the speed and heading plots here? Would be great to have it recorded and also potentially model the research vessels :)

https://github.com/UBCSailbot/local-pathfinding/blob/e20a63ef13daa1c50326c9953e96ef8c2a1cefa2/exactais_analysis/boat_tracker_data/bb_33_mmsi_538005923.png

2021-09-18 18:54 UTC, merged