Fixed convention?
UBCSailbot/local-pathfinding pull request #288
Opened 2022-07-18 05:21 UTC by jamenkaye

The utilities functions are used in several other places, so I was hesitant to to make the change there. Do still think I should fix the issue in utilities?

Also, currently the only adjustment needed is angles from -90 to 0 need to be increased by 360 to get into the new range. Should I handle if angles are smaller than -360 or larger than 360 as well? I don't think this is necessary but let me know what you think.

2022-07-19 04:38 UTC, jamenkaye commented
During the meeting today, Patrick advised that I should check the other places the utilities are used, and if possible move the change to the utility function.

2022-07-23 18:17 UTC, jamenkaye commented
As far as I could tell from looking at where `headingToBearingDegrees()` is used, it is safe to change the bounding in the function.

Changes made in this commit:
- Moved the code that bounds the angles to the `headingToBearingDegrees()` function in utilities.py
- Added a brief explanation to the function's description

Tests performed:
- changed the start and end latlons of Maui and Port Renfrew to test the boat sailing on angles in all quadrants. `/desired_heading_degrees` behaved appropriately.
- Ran local pathfinding for a few minutes and used rosparam set to change the wind angle to make sure nothing weird happened. Everything seemed normal except I noticed the warning shown in the picture attached. I think this is fine, right?
- Ran local pathfinding with `enable_los:= true`. Everything still seemed normal.

If you don't see anything you'd like me to change here, I think this issue is completely wrapped up and ready to be merged in and closed.

![Screenshot from 2022-07-23 11-10-24](https://user-images.githubusercontent.com/71156197/180617799-80f55777-bff3-4e5b-96d5-bb18d37dd0bd.png)

2022-07-24 00:25 UTC, patrick-5546 requested changes
I did not encounter the warning you did running this branch on my computer. Did you notice anything that may have caused it? Does it occur in your copy of the master branch?

Also, can you update `headingToBearingDegrees()` and `bearingToHeadingDegrees` to return a value in [0, 360) no matter the input? Then if we ever change how we use them in the future, we won't have to revisit this.

2022-07-24 00:27 UTC, patrick-5546 commented
> * Ran local pathfinding for a few minutes and used rosparam set to change the wind angle to make sure nothing weird happened. Everything seemed normal except I noticed the warning shown in the picture attached. I think this is fine, right?

I did not encounter the warning you did running this branch on my computer. Did you notice anything that may have caused it? Does it occur in the master branch as well?

2022-07-24 00:27 UTC, patrick-5546 reviewed
> * Ran local pathfinding for a few minutes and used rosparam set to change the wind angle to make sure nothing weird happened. Everything seemed normal except I noticed the warning shown in the picture attached. I think this is fine, right?

I did not encounter the warning you did running this branch on my computer. Did you notice anything that may have caused it? Does it occur in the master branch as well?

2022-07-24 06:06 UTC, jamenkaye commented
Sure, I feel like making sure its always bounded to [0, 360) is the more thorough way of doing things. I'll make the change in `headingToBearingDegrees()` and `bearingToHeadingDegrees()`. For the bounding portion of code, I'm thinking something like this:

`calculate angle #unbounded angle
if angle < 0:
    return 360 - ((-1*angle) % 360)
else
    return angle % 360`

eg, with -370, this will return 360 - 10 = 350 as desired

2022-07-24 06:07 UTC, jamenkaye commented
As for the warning, I'll keep an eye out for it in the future and see if I can figure it out. Luckily it didn't actually seem to make anything run differently. If you aren't even getting it at all, I'm guessing its just something with my computer and not anything we need to worry about.

2022-07-26 03:37 UTC, jamenkaye commented
Created a function to bound any angle to [0, 360), and used the function in both `headingToBearingDegrees()` and `bearingToHeadingDegrees`. 

Tests performed: 
- ran local pathfinding for a few minutes and changed the wind angle to make sure it didn't crash.
- tested the function with these tests: 
[Bound angle in 0 to 360 test.txt](https://github.com/UBCSailbot/local-pathfinding/files/9186300/Bound.angle.in.0.to.360.test.txt)

Ok, NOW I think its done and ready to be merged in, unless there are any other changes you'd like me to make haha

2022-08-04 18:48 UTC, patrick-5546 commented on python/utilities.py
> +            return 0
This case never occurs if `angle < 0`

2022-08-04 18:53 UTC, patrick-5546 commented
> * tested the function with these tests:
>   [Bound angle in 0 to 360 test.txt](https://github.com/UBCSailbot/local-pathfinding/files/9186300/Bound.angle.in.0.to.360.test.txt)

Can add these to the tests that circleci run every commit. They are found in the test/ directory

2022-08-04 19:09 UTC, patrick-5546 commented on python/utilities.py
> +            return 0
Nevermind, this occurs for negative multiples of 360

2022-08-04 19:10 UTC, patrick-5546 approved these changes
Great work, I just cleaned up the bounding function a bit and added the tests you wrote to our test suite

2022-08-04 19:16 UTC, merged