handled invalid AIS coordinates
UBCSailbot/local-pathfinding pull request #299
Opened 2022-08-24 07:38 UTC by jamenkaye

`AISCallback()` in Sailbot.py now removes any AIS boats with latitude outside [-90, 90] or longitude outside [-180, 180].

- Imade a utilities function `checkLatLonIsValid()` to check if a latlon is valid. Is this useful or should I delete this function and just check for validity in `AISCallback()`?
- I wanted to use the `List.remove()` function but then the loop seemed to run the incorrect number of times if I removed items from the list of ships during the loop. I don't really like that I needed to create a whole new list of AIS boats though, as this seems inefficient. Is there a better way I should do this? For example I could `pop()` the element at `[(loop index) - (number of boats removed so far)]

2022-08-24 08:04 UTC, patrick-5546 requested changes
> I wanted to use the List.remove() function but then the loop seemed to run the incorrect number of times if I removed items from the list of ships during the loop. I don't really like that I needed to create a whole new list of AIS boats though, as this seems inefficient. Is there a better way I should do this?

I think it's fine, as I'm not sure if there are any side effects of modifying `data.ships`

> Should I make it so that we can easily toggle between bounding invalid coordinates to valid equivalents vs deleting AIS boats with invalid coordinates?

I think just deleting is fine because the invalid coordinates we saw was `(91, 181)`, which I highly doubt is a real boat. Plus we only want to look at boats that are close to us

2022-08-26 16:03 UTC, jamenkaye commented on python/Sailbot.py
> +            if utils.checkLatLonIsValid(latlon(ship.lat, ship.lon)):
Makes sense, I'm addressing it in the next commit.

2022-08-26 16:14 UTC, patrick-5546 commented on python/Sailbot.py
> +                rospy.logwarn_throttle(5, "Invalid co-ordinates for "
I addressed this by taking the throttled warning out of the for-loop.

Current error message:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/65756895/186948037-0974d4bd-cdac-4a13-9335-c1f8c5197eaa.png">

2022-08-26 16:15 UTC, patrick-5546 approved these changes

2022-08-26 16:52 UTC, jamenkaye commented on python/Sailbot.py
> +                rospy.logwarn_throttle(5, "Invalid co-ordinates for "
Ok ya I think this is best, for some reason I thought the throttling wouldn't apply if the message was different each time

2022-08-26 17:29 UTC, merged